In [1]:
import pandas as pd
import numpy as np

In [2]:

df=pd.read_excel('database_new.xlsx')

In [3]:
# frames=[df1,df2]
# df=pd.concat(frames)

In [4]:
# print(df1.shape)

In [5]:
# print(df2.shape)

In [6]:
# print(df.shape)

In [7]:

#print(df)

In [8]:
# df=df.reset_index(drop=True)
# df

In [9]:
# # df=df.drop_duplicates()
# df

In [10]:
# df.sort_values(by=['wavelength'], inplace=True)


In [11]:
# df=df.reset_index(drop=True)
# df

In [14]:
train_set = df[(df['fractal_dimension'] < 2.1) | (df['fractal_dimension'] > 2.5)]
test_set = df[(df['fractal_dimension'] >= 2.1) & (df['fractal_dimension'] <=2.5)]

In [16]:
train_set['fractal_dimension'].unique()

array([1.5, 1.7, 1.9, 2.7, 2.9])

In [17]:
test_set['fractal_dimension'].unique()

array([2.1, 2.3, 2.5])

In [18]:
df.columns

Index(['wavelength', 'fractal_dimension', 'fraction_of_coating',
       'primary_particle_size', 'number_of_primary_particles',
       'vol_equi_radius_outer', 'vol_equi_radius_inner', 'equi_mobility_dia',
       'mie_epsilon', 'length_scale_factor', 'm_real_bc', 'm_im_bc',
       'm_real_organics', 'm_im_organics', 'volume_total', 'volume_bc',
       'volume_organics', 'density_bc', 'density_organics', 'mass_bc',
       'mass_organics', 'mass_total', 'mr_total/bc', 'mr_nonBC/BC', 'q_ext',
       'q_abs', 'q_sca', 'g', 'c_geo', 'c_ext', 'c_abs', 'c_sca', 'ssa',
       'mac_total', 'mac_bc', 'mac_organics'],
      dtype='object')

In [19]:
df['q_abs'].unique()

array([0.11691, 0.153  , 0.18181, ..., 1.2375 , 1.2587 , 1.319  ])